/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Algorithms.AStar;
import Algorithms.BFS;
import Image.ImageDiscretizer;
import Algorithms.DFS;
import graph.search.DisplayGraph;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author olgac
 */
public class Principal extends javax.swing.JFrame {
    private int size;
    private File image;
    private BufferedImage imageDiscretized;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Graph Search - Olga Cobaquil");
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadButton = new javax.swing.JButton();
        resizeNTextField = new javax.swing.JTextField();
        discretizeButton = new javax.swing.JButton();
        bfsButton = new javax.swing.JButton();
        dfsButton = new javax.swing.JButton();
        aStarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uploadButton.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        uploadButton.setText("Abrir");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        discretizeButton.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        discretizeButton.setText("Discretizar");
        discretizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discretizeButtonActionPerformed(evt);
            }
        });

        bfsButton.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        bfsButton.setText("BFS");
        bfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsButtonActionPerformed(evt);
            }
        });

        dfsButton.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        dfsButton.setText("DFS");
        dfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsButtonActionPerformed(evt);
            }
        });

        aStarButton.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        aStarButton.setText("A*");
        aStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        jLabel1.setText("N x N:");

        jLabel2.setText("jLabel2");

        jComboBox1.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heuristica 1", "Heuristica 2" }));

        jLabel3.setFont(new java.awt.Font("AR BONNIE", 0, 48)); // NOI18N
        jLabel3.setText("Graph Search");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setText("Imagen: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(uploadButton)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(bfsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dfsButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resizeNTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aStarButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(74, 74, 74)
                        .addComponent(discretizeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadButton)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(resizeNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discretizeButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dfsButton)
                    .addComponent(bfsButton)
                    .addComponent(aStarButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // Abrir la imagen a discretizar
        String path = System.getProperty("/documents");
        JFileChooser fileChooser = new JFileChooser(path);
        int returnValue = fileChooser.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            this.image = fileChooser.getSelectedFile();
            
            try {
                BufferedImage originalBufferedImage = ImageIO.read(this.image);
                ImageIcon icon = new ImageIcon(originalBufferedImage);
                jLabel2.setIcon(icon);
                jLabel2.setVisible(true);
                jLabel2.setText("");
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void discretizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discretizeButtonActionPerformed
        // darle un nuevo tamaño a la imagen para discretizar
        if(!image.equals(null)){
            if(!resizeNTextField.getText().isEmpty()){
                this.size = Integer.parseInt(resizeNTextField.getText());
                ImageDiscretizer imageDiscretizer = new ImageDiscretizer(this.image, this.size);
                imageDiscretized = imageDiscretizer.getImageDiscretized();
                //ImageIcon hola = new ImageIcon(imageDiscretized);
                //jLabel5.setIcon(hola);
                
            }
        }
    }//GEN-LAST:event_discretizeButtonActionPerformed

    private void bfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsButtonActionPerformed
        // TODO add your handling code here:
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        BFS bfs = new BFS(size, size, imageDiscretizer.getImageDiscretized());
        bfs.Solve();
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("BFS Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), bfs.getGraph(), bfs.getFinalPath()));
    }//GEN-LAST:event_bfsButtonActionPerformed

    private void dfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsButtonActionPerformed
        // TODO add your handling code here:
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        DFS dfs = new DFS(size, size, imageDiscretizer.getImageDiscretized());
        dfs.Solve();
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("DFS Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), dfs.getGraph(), dfs.getFinalPath()));
    }//GEN-LAST:event_dfsButtonActionPerformed

    private void aStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStarButtonActionPerformed
        // TODO add your handling code here:
        int type = jComboBox1.getSelectedIndex() + 1;
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        AStar aStar = new AStar(size, size, imageDiscretizer.getImageDiscretized());
        aStar.Solve(type);
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("A* Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), aStar.getGraph(), aStar.getFinalPath()));
    }//GEN-LAST:event_aStarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aStarButton;
    private javax.swing.JButton bfsButton;
    private javax.swing.JButton dfsButton;
    private javax.swing.JButton discretizeButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField resizeNTextField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
